package dev.lilkuzco.kinetics.constants;

import dev.lilkuzco.kinetics.profile.EngineFrame;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates the scale-audit report required by invariant I11.
 *
 * <p>The point of I11 is that the mapping from reality to game must always be inspectable and
 * defensible. Anyone can ask "why is the planet 342.5 km across?" and get an answer with the
 * real value, the game value, the factor between them and the reason - without reading any
 * code.
 *
 * <p>The audit also <b>verifies</b> rather than transcribes: every declared factor is checked
 * against its own real and game values, and a factor that does not reconstruct its real value
 * is reported as an inconsistency. A scale audit that only echoed what the constants file
 * claimed would catch nothing.
 *
 * <p>This writes {@code SCALE-AUDIT.md}. That file is generated - patch this class, never the
 * markdown, or the next run silently destroys the edit.
 */
public final class ScaleAudit {

    private final Constants k;

    public ScaleAudit(Constants k) { this.k = k; }

    public static void main(String[] args) throws IOException {
        Path out = Path.of(args.length > 0 ? args[0] : "SCALE-AUDIT.md");
        String report = new ScaleAudit(Constants.get()).render();
        Files.writeString(out, report, StandardCharsets.UTF_8);
        System.out.println("wrote " + out.toAbsolutePath() + " (" + report.length() + " bytes)");
    }

    /** Every declared factor that does not reconstruct its own real value. */
    public List<Constants.ScaledConstant> inconsistencies() {
        return k.scaledConstants().stream().filter(c -> !c.factorIsConsistent()).toList();
    }

    public String render() {
        StringBuilder sb = new StringBuilder();
        List<Constants.ScaledConstant> scaled = k.scaledConstants();

        sb.append("# SCALE-AUDIT.md — lilkuzco_kinetics\n\n");
        sb.append("**Generated by `dev.lilkuzco.kinetics.constants.ScaleAudit`. Do not edit by "
                + "hand — patch the generator.**\n\n");
        sb.append("Invariant I11 requires that every constant scaled for Minecraft be listed "
                + "with its real value, its game value and the factor between them, so the "
                + "mapping from reality to game is always inspectable.\n\n");

        sb.append("## The short version\n\n");
        sb.append("Almost nothing is scaled. One block is one metre, gravity is Earth's "
                + "9.80665 m/s², air is 1.225 kg/m³ at sea level, and every aerodynamic and "
                + "propulsion coefficient is its real published value. **Three** constants "
                + "depart from reality, and each buys something specific:\n\n");
        sb.append("| # | Constant | Factor | What it buys |\n");
        sb.append("|---|---|---|---|\n");
        sb.append("| 1 | atmospheric scale height | 154.55× thinner column | "
                + "Folds 8,500 m of atmosphere into the 257 m Minecraft can build in, so "
                + "altitude is a real tactical variable instead of decoration. |\n");
        sb.append("| 2 | planet radius | 18.60× smaller | "
                + "The free parameter. Fixing gravity at Earth's value and demanding a "
                + "20-minute orbit determines the radius; 342.5 km is what came out. |\n");
        sb.append("| 3 | exhaust velocity | 4.215× lower | "
                + "Restores the real difficulty of reaching orbit. A smaller planet is genuinely "
                + "easier to orbit; without this, a mass ratio of 2.1 would do and staging "
                + "would be pointless. |\n\n");

        sb.append("Everything else in the table below is a *derived consequence* of those "
                + "three, or a real value recorded alongside its game counterpart for "
                + "reference.\n\n");

        sb.append("## Full table\n\n");
        sb.append("| Constant | Game value | Real value | Factor | Units | Consistent? |\n");
        sb.append("|---|---:|---:|---:|---|:--:|\n");
        for (Constants.ScaledConstant c : scaled) {
            sb.append(String.format("| `%s` | %s | %s | %s | %s | %s |%n",
                    c.path(), fmt(c.gameValue()), fmt(c.realValue()), fmt(c.scaleFactor()),
                    c.units().isEmpty() ? "—" : c.units(),
                    c.factorIsConsistent() ? "yes" : "**NO**"));
        }
        sb.append('\n');

        List<Constants.ScaledConstant> bad = inconsistencies();
        if (bad.isEmpty()) {
            sb.append("Every declared factor reconstructs its own real value to within 0.1%. "
                    + "The audit checks this rather than trusting the declaration — a factor "
                    + "that disagreed with its own values would be a bookkeeping bug, and it "
                    + "would appear here rather than in a trajectory a month later.\n\n");
        } else {
            sb.append("### Inconsistent factors\n\n");
            for (Constants.ScaledConstant c : bad) {
                sb.append(String.format("- **`%s`** — declared factor %s, but %s × %s = %s, "
                        + "not %s%n", c.path(), fmt(c.scaleFactor()), fmt(c.gameValue()),
                        fmt(c.scaleFactor()), fmt(c.gameValue() * c.scaleFactor()),
                        fmt(c.realValue())));
            }
            sb.append('\n');
        }

        sb.append("## Derived figures\n\n");
        appendDerived(sb);

        sb.append("\n## Source notes\n\n");
        sb.append("Every scaled constant carries the reasoning for its value.\n\n");
        for (Constants.ScaledConstant c : scaled) {
            sb.append("**`").append(c.path()).append("`** — ").append(c.sourceNote()).append("\n\n");
        }
        return sb.toString();
    }

    private void appendDerived(StringBuilder sb) {
        double g0 = k.d("gravity.g0");
        double radius = k.d("orbit.planet_radius");
        double mu = k.d("orbit.mu");
        double refAlt = k.d("orbit.reference_orbit_altitude");
        double r = radius + refAlt;
        double vCirc = Math.sqrt(mu / r);
        double period = 2.0 * Math.PI * Math.sqrt(r * r * r / mu);
        double escape = Math.sqrt(2.0) * vCirc;
        double budget = k.d("orbit.delta_v_to_orbit");
        double dayPeriod = k.d("world.day_seconds");

        EngineFrame frame = EngineFrame.of(k);
        double ispVac = k.d("propulsion.isp_reference.kerolox_vacuum");
        double veReal = frame.realExhaustVelocity(ispVac);
        double veGame = frame.exhaustVelocity(ispVac);
        double massRatio = Math.exp(budget / veGame);
        double realMassRatio = Math.exp(9400.0 / (311.0 * 9.80665));

        sb.append("These are computed from the constants above, not stored. They are what the "
                + "scaling actually produces.\n\n");
        sb.append("| Quantity | Value | Real analogue |\n|---|---:|---|\n");
        sb.append(row("Surface gravity", fmt(g0) + " m/s²", "Earth, exactly — unscaled"));
        sb.append(row("Planet radius", fmt(radius) + " m", "Earth 6,371,000 m"));
        sb.append(row("μ = g₀R² (derived)", fmt(mu) + " m³/s²", "Earth 3.986e14"));
        sb.append(row("Reference orbit altitude", fmt(refAlt) + " m", "LEO ~400,000 m"));
        sb.append(row("Orbital velocity there", String.format("%.2f m/s", vCirc), "LEO ~7,670 m/s"));
        sb.append(row("Orbital period there", String.format("%.2f s", period),
                String.format("target %.0f s (one Minecraft day), error %.4f%%",
                        dayPeriod, Math.abs(period - dayPeriod) / dayPeriod * 100.0)));
        sb.append(row("Escape velocity there", String.format("%.2f m/s", escape),
                "√2 × circular, by construction"));
        sb.append(row("Δv budget to orbit", fmt(budget) + " m/s", "LEO 9,400 m/s"));
        sb.append(row("Losses fraction", String.format("%.2f%%", (budget / vCirc - 1.0) * 100.0),
                "reality pays ~22.6% over orbital velocity"));
        sb.append(row("Kerolox v_e (real)", String.format("%.1f m/s", veReal),
                "311 s × g₀, unscaled"));
        sb.append(row("Kerolox v_e (effective)", String.format("%.1f m/s", veGame),
                "divided by the 4.215 scale"));
        sb.append(row("Mass ratio to orbit", String.format("%.2f", massRatio),
                String.format("real LEO on kerolox: %.2f", realMassRatio)));

        double scaleHeight = k.d("atmosphere.scale_height");
        double rho0 = k.d("atmosphere.rho_sea_level");
        double karman = k.d("atmosphere.karman_altitude_game");
        sb.append(row("Atmospheric column mass", String.format("%.1f kg/m²", rho0 * scaleHeight),
                String.format("Earth %.0f kg/m² — ours is %.0f× lighter, which is why a reentry "
                        + "vehicle here needs a large drag area for its mass",
                        1.225 * 8500.0, (1.225 * 8500.0) / (rho0 * scaleHeight))));
        sb.append(row("Density at the Karman line",
                String.format("%.6f kg/m³", rho0 * Math.exp(-karman / scaleHeight)),
                String.format("the real density near %.0f km", karman * (8500.0 / scaleHeight) / 1000.0)));
    }

    private static String row(String a, String b, String c) {
        return "| " + a + " | " + b + " | " + c + " |\n";
    }

    private static String fmt(double v) {
        if (v == Math.floor(v) && Math.abs(v) < 1e15 && Math.abs(v) >= 1.0) {
            return String.format("%,d", (long) v);
        }
        if (Math.abs(v) >= 1e6 || (Math.abs(v) < 1e-4 && v != 0.0)) {
            return String.format("%.6g", v);
        }
        return String.format("%.6f", v).replaceAll("0+$", "").replaceAll("\\.$", "");
    }
}
